# Mod
modId=jecalculation
modName=JustEnoughCalculation
modDescription=A simple mod to help you with recipe calculation.
modAuthor=towdium
modVersion=4.0.5
modLicense=MIT
modSourcesURL=https://github.com/Towdium/JustEnoughCalculation
modIssuesURL=https://github.com/Towdium/JustEnoughCalculation/issues

# Dependencies
minecraftVersion=26.1.2
fabricVersion=0.19.3
loomVersion=1.16-SNAPSHOT
mixinVersion=0.12.5+mixin.0.8.5
clothConfigVersion=26.1.154
modmenuVersion=18.0.0-alpha.8

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
